<?xml version="1.0"?>
<robot name="tracer_ur5e_mobile_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- *********************** -->
  <!-- TRACER AGILEX DEFINITION -->
  <!-- *********************** -->

  <!-- Declare arguments (if any extras are provided) -->
  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="urdf_extras" default="empty.urdf" />

  <!-- Include the Tracer wheel and castor macros -->
  <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_1.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/tracer_wheel_2.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fr_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fl_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rr_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rl_castor.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fr_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/fl_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rr_wheel.xacro" />
  <xacro:include filename="$(find tracer_description)/urdf/rl_wheel.xacro" />

  <!-- Tracer properties -->
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="base_x_size" value="0.62"/>
  <xacro:property name="base_y_size" value="0.585"/>
  <xacro:property name="base_z_size" value="0.235"/>
  <xacro:property name="wheelbase" value="0.34"/>
  <xacro:property name="track" value="0.37910"/>
  <xacro:property name="castor_length" value="0.002"/>
  <xacro:property name="castor_radius" value="0.03724"/>
  <xacro:property name="wheel_vertical_offset" value="-0.082"/>
  <xacro:property name="castor_offset" value="0.03"/>
  <xacro:property name="wheel_length" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.16"/>

  <!-- Base link of the tracer -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://tracer_description/meshes/tracer_base_link_no_wheel.dae" />
      </geometry>
    </collision>
  </link>

  <!-- Inertial link for the tracer (used for proper mass/inertia) -->
  <link name="inertial_link">
    <inertial>
      <mass value="132.3898489950015" />
      <origin xyz="0.015 0.0231316650320557 0" />
      <inertia ixx="0.185196122711036" 
               ixy="4.30144213829512E-08" 
               ixz="5.81037523686401E-08" 
               iyy="0.364893736238929" 
               iyz="-0.000386720198091934" 
               izz="0.223868521722778" />
    </inertial>
  </link>

  <!-- Fixed joint connecting base_link to inertial_link -->
  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- Instantiate tracer wheels and castors -->
  <!-- Wheels: front-right and front-left -->
  <xacro:tracer_wheel_1 wheel_prefix="right">
    <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:tracer_wheel_1>
  <xacro:tracer_wheel_2 wheel_prefix="left">
    <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
  </xacro:tracer_wheel_2>
  <!-- Castor wheels -->
  <xacro:fl_castor wheel_prefix="fl_castor">
    <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:fl_castor>
  <xacro:fr_castor wheel_prefix="fr_castor">
    <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:fr_castor>
  <xacro:rr_castor wheel_prefix="rr_castor">
    <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:rr_castor>
  <xacro:rl_castor wheel_prefix="rl_castor">
    <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
  </xacro:rl_castor>
  <!-- Alternative wheel placements -->
  <xacro:fl_wheel wheel_prefix="fl">
    <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:fl_wheel>
  <xacro:fr_wheel wheel_prefix="fr">
    <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:fr_wheel>
  <xacro:rr_wheel wheel_prefix="rr">
    <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:rr_wheel>
  <xacro:rl_wheel wheel_prefix="rl">
    <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
  </xacro:rl_wheel>

  <!-- Additional tracer definitions -->
  <xacro:include filename="$(arg urdf_extras)" />
  <xacro:include filename="$(find tracer_description)/urdf/tracer.gazebo" />

  <!-- ***************************** -->
  <!-- END OF TRACER DEFINITION -->
  <!-- ***************************** -->

  <!-- ***************************** -->
  <!-- UR5e ROBOT DEFINITION (with UR5e_ prefix) -->
  <!-- ***************************** -->

  <!-- Note: This section is adapted from the universal_robot/ur_description/urdf/ur5.xacro file.
       All links and joints are renamed with the prefix "ur5e_" to avoid conflicts. -->

  <!-- UR5e Base Link -->
  <link name="ur5e_base_link">
    <visual>
      <origin rpy="0 0 3.14159" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/base.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 3.14159" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/base.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="4.0" />
      <origin rpy="0 0 0" xyz="0 0 0" />
      <inertia ixx="0.00443333156" ixy="0.0" ixz="0.0" iyy="0.00443333156" iyz="0.0" izz="0.0072" />
    </inertial>
  </link>

  <!-- Fixed joint mounting the UR5e on top of the tracer.
       Adjust the origin as necessary for proper placement. -->
  <joint name="tracer_to_ur5e_mount" type="fixed">
    <parent link="inertial_link"/>
    <child link="ur5e_base_link"/>
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
  </joint>

  <!-- UR5e Shoulder Link -->
  <link name="ur5e_shoulder_link">
    <visual>
      <origin rpy="0 0 3.14159" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/shoulder.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 3.14159" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/shoulder.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="3.7" />
      <origin rpy="0 0 0" xyz="0 0 0" />
      <inertia ixx="0.014972352344389999" ixy="0.0" ixz="0.0" iyy="0.014972352344389999" iyz="0.0" izz="0.01040625" />
    </inertial>
  </link>

  <!-- UR5e Upper Arm Link -->
  <link name="ur5e_upper_arm_link">
    <visual>
      <origin rpy="1.5708 0 -1.5708" xyz="0 0 0.13585" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/upperarm.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 -1.5708" xyz="0 0 0.13585" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/upperarm.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="8.393" />
      <origin rpy="0 1.5708 0" xyz="-0.2125 0 0.136" />
      <inertia ixx="0.1338857818623325" ixy="0.0" ixz="0.0" iyy="0.1338857818623325" iyz="0.0" izz="0.0151074" />
    </inertial>
  </link>

  <!-- UR5e Forearm Link -->
  <link name="ur5e_forearm_link">
    <visual>
      <origin rpy="1.5708 0 -1.5708" xyz="0 0 0.0165" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/forearm.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 -1.5708" xyz="0 0 0.0165" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/forearm.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="2.275" />
      <origin rpy="0 1.5708 0" xyz="-0.196125 0 0.0165" />
      <inertia ixx="0.03121679102890359" ixy="0.0" ixz="0.0" iyy="0.03121679102890359" iyz="0.0" izz="0.004095" />
    </inertial>
  </link>

  <!-- UR5e Wrist 1 Link -->
  <link name="ur5e_wrist_1_link">
    <visual>
      <origin rpy="1.5708 0 0" xyz="0 0 -0.093" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/wrist1.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 0" xyz="0 0 -0.093" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/wrist1.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="1.219" />
      <origin rpy="0 0 0" xyz="0 0 0" />
      <inertia ixx="0.0020138887777775" ixy="0.0" ixz="0.0" iyy="0.0020138887777775" iyz="0.0" izz="0.0021942" />
    </inertial>
  </link>

  <!-- UR5e Wrist 2 Link -->
  <link name="ur5e_wrist_2_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.095" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/wrist2.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 -0.095" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/wrist2.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="1.219" />
      <origin rpy="0 0 0" xyz="0 0 0" />
      <inertia ixx="0.0018310388509175" ixy="0.0" ixz="0.0" iyy="0.0018310388509175" iyz="0.0" izz="0.0021942" />
    </inertial>
  </link>

  <!-- UR5e Wrist 3 Link -->
  <link name="ur5e_wrist_3_link">
    <visual>
      <origin rpy="1.5708 0 0" xyz="0 0 -0.0818" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/visual/wrist3.dae" />
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0" />
      </material>
    </visual>
    <collision>
      <origin rpy="1.5708 0 0" xyz="0 0 -0.0818" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur5/collision/wrist3.stl" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1879" />
      <origin rpy="0 0 0" xyz="0 0 -0.01525" />
      <inertia ixx="8.062472608343e-05" ixy="0.0" ixz="0.0" iyy="8.062472608343e-05" iyz="0.0" izz="0.0001321171875" />
    </inertial>
  </link>

  <!-- UR5e Joints (serial chain) -->
  <joint name="ur5e_shoulder_pan_joint" type="revolute">
    <parent link="ur5e_base_link"/>
    <child link="ur5e_shoulder_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.089159" />
    <axis xyz="0 0 1" />
    <limit effort="150.0" lower="-6.283185307179586" upper="6.283185307179586" velocity="3.141592653589793" />
  </joint>

  <joint name="ur5e_shoulder_lift_joint" type="revolute">
    <parent link="ur5e_shoulder_link"/>
    <child link="ur5e_upper_arm_link"/>
    <origin rpy="1.5708 0 0" xyz="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="150.0" lower="-6.283185307179586" upper="6.283185307179586" velocity="3.141592653589793" />
  </joint>

  <joint name="ur5e_elbow_joint" type="revolute">
    <parent link="ur5e_upper_arm_link"/>
    <child link="ur5e_forearm_link"/>
    <origin rpy="0 0 0" xyz="-0.425 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="150.0" lower="-3.14159" upper="3.14159" velocity="3.14159" />
  </joint>

  <joint name="ur5e_wrist_1_joint" type="revolute">
    <parent link="ur5e_forearm_link"/>
    <child link="ur5e_wrist_1_link"/>
    <origin rpy="0 0 0" xyz="-0.39225 0 0.10915" />
    <axis xyz="0 0 1" />
    <limit effort="28.0" lower="-6.28319" upper="6.28319" velocity="3.14159" />
  </joint>

  <joint name="ur5e_wrist_2_joint" type="revolute">
    <parent link="ur5e_wrist_1_link"/>
    <child link="ur5e_wrist_2_link"/>
    <origin rpy="1.5708 0 0" xyz="0 -0.09465 0" />
    <axis xyz="0 0 1" />
    <limit effort="28.0" lower="-6.28319" upper="6.28319" velocity="3.14159" />
  </joint>

  <joint name="ur5e_wrist_3_joint" type="revolute">
    <parent link="ur5e_wrist_2_link"/>
    <child link="ur5e_wrist_3_link"/>
    <origin rpy="1.5708 3.14159 3.14159" xyz="0 0 0.0823" />
    <axis xyz="0 0 1" />
    <limit effort="28.0" lower="-6.28319" upper="6.28319" velocity="3.14159" />
  </joint>

  <!-- Define UR5e flange and tool frames -->
  <link name="ur5e_flange">
    <!-- (Visual and collision can be added as needed) -->
  </link>
  <joint name="ur5e_wrist_3_to_flange" type="fixed">
    <parent link="ur5e_wrist_3_link"/>
    <child link="ur5e_flange"/>
    <origin rpy="0 -1.5708 -1.5708" xyz="0 0 0" />
  </joint>

  <link name="ur5e_tool0">
    <!-- (Visual and collision for the tool can be defined here) -->
  </link>
  <joint name="ur5e_flange_to_tool0" type="fixed">
    <parent link="ur5e_flange"/>
    <child link="ur5e_tool0"/>
    <origin rpy="1.5708 0 1.5708" xyz="0 0 0" />
  </joint>
  
  <!-- ***************************** -->
  <!-- END OF UR5e DEFINITION -->
  <!-- ***************************** -->

  <!-- (Optional: you can add Gazebo plugins or transmissions for the UR5e here if needed) -->

</robot>
